### ISSUE TITLE
Shared Components Image

### ISSUE THREAD

**Issue by AlexisAth** [ashishtheapexian/Material-cards#1]
Hello there, I have installed your plug-in and it works like a charm!
Firstly, I want to set an image I have already uploaded to apex shared components, as image card. Am I able to make this work? 
Also, one more thing, I would like to change the font and colour of the card text. Can you help me with that?
Best regards,
Alex.

EDIT! After 2 hours of flawless work, the plug-in stopped working and it only shows a loading symbol.

**Comment by ashishtheapexian** [comment]
Hi AlexisAth,
Thanks for it.
Ans 1. You can make url in sql query for an image from anywhere.
Ans 2. If you are asking about the flip Card text color for details then i have to make few changes. let me know if i getting correct? **Or you can try with below example text in card text like below**

`<font color="red">This is some text! </font>`

Can you please share the console display for further issue you got in loading?

**Comment by ashishtheapexian** [comment]
Please try below.

![image](https://user-images.githubusercontent.com/13847003/74146921-26b4b000-4c28-11ea-937a-28c7ea910aad.png)



![image](https://user-images.githubusercontent.com/13847003/74146930-2e745480-4c28-11ea-997b-7d0d2e687610.png)
